[package]
name = "dragit"
version = "0.1.0"
authors = ["sireliah"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = [ "unstable" ] }
blurz = { git = "https://github.com/szeged/blurz.git" }
cairo-rs = "^0"
dbus = "0.6"
directories = "2.0.2"
futures = "0.3.4"
gdk = "^0"
gio = "^0"
glib = "^0"
gtk = "0.8.1"
libp2p = "0.17.0"
percent-encoding = "2.1.0"
rust-crypto = "^0.2"
