[package]
name = "dragit"
version = "0.1.0"
authors = ["sireliah <sajuukk@gmail.com>"]

[dependencies]
blurz = "0.2.3"
dbus = "0.6"
cairo-rs = { git = "https://github.com/gtk-rs/cairo.git"}
gtk = { git = "https://github.com/gtk-rs/gtk.git" }
gio = { git = "https://github.com/gtk-rs/gio.git" }
gdk = { git = "https://github.com/gtk-rs/gdk.git" }

