[package]
name = "dragit"
version = "0.4.0"
authors = ["sireliah"]
edition = "2018"
build = "build.rs"

[dependencies]
async-std = { version = "1.7.0", features = [ "unstable" ] }
bytesize = "1.0.0"
directories-next = "2.0.0"
futures = "0.3.5"
gdk = "^0"
gio = "^0"
glib = "^0"
gtk = { version = "0.8.1", features = [ "v3_18" ] }
hex = "0.4.2"
hostname = "0.3.0"
libp2p = { version = "0.24.0", features = [ "dns", "websocket", "mplex", "mdns-async-std", "tcp-async-std", "noise" ], default-features = false }
libp2p-secio = "0.23.0"
log = "0.4.8"
env_logger = "0.7"
md-5 = "0.8.0"
pnet = "0.27.2"
prost = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2.0"
toml = "0.5.7"
smallvec = "1.6.1"

[build-dependencies]
prost-build = { version = "0.6.1" }

[target.'cfg(unix)'.dependencies]
pnet_datalink = "0.26.0"

[target.'cfg(windows)'.dependencies]
ipconfig = "0.2.2"

[target.'cfg(windows)'.build-dependencies]
autovcpkg = { git = "https://github.com/fungos/autovcpkg.git", version = "0.1.2019-10", features = ["gtk", "cairo"]}
